###
POST https://sqlite-101-ad9w.onrender.com/api/greetings
Content-Type: application/json

{
    "language" : "Afrikaans",
    "greeting" : "Goeie dag" 
}

###
GET https://sqlite-101-ad9w.onrender.com/api/greetings
Content-Type: application/json

{
    "language" : "Afrikaans",
    "greeting" : "Goeie dag" 
}